name             'postgresql_shm'
maintainer       'Roy Ratcliffe'
maintainer_email 'roy@pioneeringsoftware.co.uk'
license          'All rights reserved'
description      'Installs/Configures postgresql_shm'
long_description 'Installs/Configures postgresql_shm'
version          '0.1.0'
